#!/usr/bin/python
#version 1.0
import requests
import sys
apiKey = '<insert your Yandex ApiKey here>'
text = ''
lang = ' '
for par in sys.argv[1:]:
	if '--' in par:
		lang = par[2:]
	else:
		text += par
		text += ' '
setup = {'key' : apiKey, 'text' : text, 'lang' : lang, 'format' : 'plain', 'options' : '', 'callback' : 'call'}
r = requests.get('https://translate.yandex.net/api/v1.5/tr.json/translate', params = setup)
codePos = r.text.index('"code') + 7
code = r.text[codePos : codePos + 3]
if code == '200':
	posText = (r.text).index('"text"') + 9
	print(r.text[posText : -4])
else:
	print('Error ' + code)
